# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LADY MAFIA
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ladymafia.rocks" # the base hostname & protocol for your site
twitter_username: weareladymafia
github_username:  ladymafia

# Build settings
markdown: kramdown

#Output
# permalink: page.title

jekyll_ga:
  service_account_email: account-1@ladymafia0.iam.gserviceaccount.com    # service account email address
  key_file: ga-key.p12                                                   # service account private key file
  key_secret: notasecret                                                 # service account private key's password
  profileID: ga:112135013                                                # profile ID
  start: last month                                                      # Beginning of report
  end: now                                                               # End of report
  metric: ga:pageviews                                                   # Metric code
  # segment:                                                               # optional
  # filters:                                                               # optional
  sort: true                                                             # Sort posts by this metric

exclude: [".gitignore", ".gitattributes", ".gitmodules", "LICENSE", "Rakefile", "CHANGELOG.md", "Gemfile", "Gemfile.lock", "_drafts", "instagram.html", "ga-key.p12"]
